### ISSUE TITLE
Add installation steps

### ISSUE THREAD

**Issue by zenorocha** [ayushpokh/dracula_scrivener#2]
Hey @ayushpokh, looks like you forgot to add the installation instructions on the INSTALL.md file.

Can you update? We need that before adding it to the website.

**Comment by zenorocha** [comment]
Still waiting on this one to add to the website.

**Comment by ghost** [comment]
Sorry! Not in the habit of using git/github yet! Didn't see this as pending. Oof.

**Comment by ghost** [comment]
Updated!
