### ISSUE TITLE
Can't install in macOS

### ISSUE THREAD

**Issue by jandreaucodes** [ayushpokh/dracula_scrivener#3]
When trying to install manually, Scrivener does not let you select the Dracula.scrtheme

If you double click on it and tell macOS to open with Scrivener, you get an error: "The document “Dracula.scrtheme” could not be opened. Scrivener cannot open files in the “Scrivener Document” format."

**Comment by JuHyung-Son** [comment]
me too

**Comment by patrick-armitage** [comment]
Any chance of OSX support, or guidance on a fork to add it?

cc @zenorocha how you doing boss?  Worked with you at Liferay back in the day!

**Comment by v0lkan** [comment]
@patrick-armitage in case you are still looking, renaming the theme from `dracula.scrtheme` to `dracula.stheme` worked for me.

**Comment by ghost** [comment]
Hi friends, I've created a mac version of this and uploaded.  Let me know if this works.

**Comment by JuHyung-Son** [comment]
good it works well
