### ISSUE TITLE
how to modify some fonts of the menu bar？

### ISSUE THREAD

**Issue by ghost** [ayushpokh/dracula_scrivener#4]
Thank you for making such a great theme. But I have a question, as shown in the picture, these fonts on the menu bar, it looks a bit ghosted, I want it to keep the existing color, but the font is set to be the same as other menu bar fonts, how can I modify it? 

Operating system: Windows 11
Scrivener version: 3.1.4.1
![QQ截图20230531113115](https://github.com/dracula/scrivener/assets/8412100/4a23ae08-ffb2-414a-a3be-ef6431c5ceb6)

**Comment by magge-faf** [comment]
@chiusuan I think, you are looking for this menu point, your issue is unrelated to the theme itself, then a more general setting for Scrivener:

![image](https://github.com/dracula/scrivener/assets/101107758/e4ab75a5-0f35-48bd-9471-ce81b032ea1d)
